import type { Metadata } from "next";
import ReactQueryProvider from "./ReactQueryProvider";
import Navbar from "./components/shared/navbar";
import Footer from "./components/shared/footer";
import CartSidebar from "./components/CartSidebarWrapper";
import { Providers } from "./providers/providers";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bashions Ecolights",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-sans"
        style={{
          fontFamily: "Open Sans, 'Helvetica Neue', Helvetica, Arial, sans-serif",
        }}
      >
        <Providers>
            <Navbar />
            <CartSidebar />
            <main className="relative">
          <ReactQueryProvider>
              {children}
              <Toaster richColors position="top-right" /> 
          </ReactQueryProvider>
            </main>
            <Footer />
        </Providers>
      </body>
    </html>
  );
}
